---
ID: "2bd2290b-e8e5-4522-893f-37cfe8ecb8af"
Parent: "3b7721cd-1431-410c-8c3a-cc5618b47f7c"
Template: "3b7721cd-1431-410c-8c3a-cc5618b47f7c"
Path: /sitecore/templates/Project/Wageworks/Content Types/Site Root/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181213T162843Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
