---
ID: "9e1369a3-454f-4edb-add3-17b63dd8adf3"
Parent: "9f93fec6-fd95-47d9-ae56-cec1225c044f"
Template: "9f93fec6-fd95-47d9-ae56-cec1225c044f"
Path: /sitecore/templates/Project/Common/Content Types/Promotion Link Menu Item/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{390333C8-751B-4332-84A3-6360B969A19F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1b483e91-d8c4-4d19-ba03-462074b55936"
      Hint: NavigationTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150910T044109Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
