---
ID: "e603e240-530a-466e-b319-3d715ebe4d64"
Parent: "5d614cca-f79f-496d-bbb7-b8b69b47c6f6"
Template: "5d614cca-f79f-496d-bbb7-b8b69b47c6f6"
Path: /sitecore/templates/Project/Wageworks/Common/Content Types/Teasers/Teaser/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181211T165503Z
