---
ID: "5c3bf54a-f407-4960-947a-ad003f04154a"
Parent: "f67bd18d-7572-4290-87f4-a5e473865afa"
Template: "f67bd18d-7572-4290-87f4-a5e473865afa"
Path: /sitecore/templates/Project/Common/Content Types/Search/Page Count Option/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180315T165949Z
    - ID: "37e42c04-25f3-4fbe-95ef-d3959d733af3"
      Hint: Page Count Label
      Value: $name per page
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
