// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Wageworks.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {3F79A9D0-2210-49E4-BF67-DD8E022900F1} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/_CallToAction
	/// </summary>
	[SitecoreType(TemplateId = "{3F79A9D0-2210-49E4-BF67-DD8E022900F1}")]
	public partial interface ICallToAction
	{
		#region Content

	    [SitecoreField(FieldId = "{27C1025D-DEF9-4108-9FC4-94DEE8716513}")]
		Link Link { get; set; }

	    [SitecoreField(FieldId = "{4E0F59F5-6EE0-40A2-8D79-5E44622A713E}")]
		string Name { get; set; }

		/// <summary>
		/// Render as Link instead of Button
		/// </summary>
	    [SitecoreField(FieldId = "{BF652209-034C-49D5-A019-D230F3E526AA}")]
		bool RenderAsLink { get; set; }

		#endregion

	}
}
