// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace WageWorks.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {A543133D-0FEF-4FCA-9E97-0E5A5065E58C} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/_ConditionalPromo
	/// </summary>
	[SitecoreType(TemplateId = "{A543133D-0FEF-4FCA-9E97-0E5A5065E58C}")]
	public partial interface IConditionalPromo
	{
		#region Conditions

	    [SitecoreField(FieldId = "{610F2FD0-43A1-454E-9A6D-E0FF49A7C967}")]
		string ExpectedValue { get; set; }

	    [SitecoreField(FieldId = "{4E5891BE-CE79-4B64-A5E2-1DC6E2DFC883}")]
		Guid SourceField { get; set; }

		#endregion

	}
}
