// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace WageWorks.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {20A56D46-F5E3-4DB8-8B96-081575363D44} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/_DynamicTeaser
	/// </summary>
	[SitecoreType(TemplateId = "{20A56D46-F5E3-4DB8-8B96-081575363D44}")]
	public partial interface IDynamicTeaser
	{
        [SitecoreId]
        Guid Id { get; set; }
		#region Content
		/// <summary>
		/// Index of the active teaser
		/// </summary>
	    [SitecoreField(FieldId = "{9E942565-677F-491C-A0AC-6B930E37342A}")]
		int Active { get; set; }

		/// <summary>
		/// Number of Teasers
		/// </summary>
	    [SitecoreField(FieldId = "{A33F9523-96C4-4E42-B6D7-1E861718D373}")]
		int Count { get; set; }

		#endregion

	}
}
