// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace WageWorks.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {C80D124B-B9AC-432E-8C26-DBF3A7F18D20} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/_Headline
	/// </summary>
	[SitecoreType(TemplateId = "{C80D124B-B9AC-432E-8C26-DBF3A7F18D20}")]
	public partial interface IHeadline
	{
		#region Content

		/// <summary>
		/// ティザー アイコン
		/// </summary>
	    [SitecoreField(FieldId = "{3AF50903-63A9-464B-A375-B94983624E7D}")]
		Link TeaserIcon { get; set; }

		/// <summary>
		/// Teaser title
		/// </summary>
	    [SitecoreField(FieldId = "{4A59D072-5B41-4A79-A157-2B2CCAC10F2B}")]
		string TeaserTitle { get; set; }

		#endregion

	}
}
