// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace Vista.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {E90D00B6-0BE9-48E0-9C3F-047274024270} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/Icon
	/// </summary>
	[SitecoreType(TemplateId = "{E90D00B6-0BE9-48E0-9C3F-047274024270}")]
	public partial interface IIcon
	{
		#region Content

		/// <summary>
		/// Css クラス
		/// </summary>
	    [SitecoreField(FieldId = "{585F89D1-570C-4F66-A6EC-195A8DA654E1}")]
		string CssClass { get; set; }

		#endregion

	}
}
