// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace WageWorks.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {8F8BD4FF-2814-4FBE-B6E7-2712DF34E630} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/_Promotion
	/// </summary>
	[SitecoreType(TemplateId = "{8F8BD4FF-2814-4FBE-B6E7-2712DF34E630}")]
	public partial interface IPromotion
	{
		#region Content

	    [SitecoreField(FieldId = "{EEADA406-E3C3-4DC6-BFDF-3DF1C3D1B665}")]
		string Badge { get; set; }

	    [SitecoreField(FieldId = "{0E23B8D1-E4CB-4F4A-B14C-2D95BB6412E3}")]
		string Body { get; set; }

	    [SitecoreField(FieldId = "{DCCADB4D-CB5A-40E2-9A98-00F538A61E8B}")]
		string Headline { get; set; }

	    [SitecoreField(FieldId = "{37A3A91D-DB7E-4C59-9736-23B9CC673C10}")]
		string SectionTitle { get; set; }

	    [SitecoreField(FieldId = "{442B8E3A-BD43-446D-B7D2-6DD868593E88}")]
		Guid Theme { get; set; }

	    [SitecoreField(FieldId = "{A5AB15E6-DEA2-4C14-9B2A-12241A58445F}")]
		string Title { get; set; }

		#endregion

		#region Media

	    [SitecoreField(FieldId = "{A8E58453-0B0C-445B-9D2F-25B4D2E9F0FD}")]
		Image BackgroundImage { get; set; }

	    [SitecoreField(FieldId = "{B11D8944-412F-4063-8FFE-E8BB6DAF7BAA}")]
		File BackgroundVideo { get; set; }

	    [SitecoreField(FieldId = "{D7AC5ADC-24B0-419E-835A-FF71C142E83C}")]
		Image ForegroundImage { get; set; }

	    [SitecoreField(FieldId = "{A95EBC57-12C9-45B7-9DF9-E0CD49C71E4D}")]
		Link ForegroundVideo { get; set; }

		#endregion

	}
}
