// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace WageWorks.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {20748D57-4EF6-49A8-B7E6-13818795E3B5} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/_TeasersParameters
	/// </summary>
	[SitecoreType(TemplateId = "{20748D57-4EF6-49A8-B7E6-13818795E3B5}")]
	public partial interface ITeasersParameters
	{
	}
}
