// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace WageWorks.Feature.Teasers.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    using Teasers;


	/// <summary>
	/// Represents a mapped type for item {FEC0E62A-01FD-40E5-88F3-E5229FE79527} in Sitecore.
	/// Path: /sitecore/templates/Feature/Teasers/_TeaserContent
	/// </summary>
	[SitecoreType(TemplateId = "{FEC0E62A-01FD-40E5-88F3-E5229FE79527}")]
	public partial interface ITeaserContent : IHeadline
	{
		#region Content

		/// <summary>
		/// Label
		/// </summary>
	    [SitecoreField(FieldId = "{3F7E7E3A-4E8E-4639-B079-FC5AEFF172F5}")]
		string TeaserLabel { get; set; }

		/// <summary>
		/// Teaser Image
		/// </summary>
	    [SitecoreField(FieldId = "{0F6B5546-E0AB-4487-81DE-640C1AA1B65B}")]
		Image TeaserImage { get; set; }

		/// <summary>
		/// Teaser Link
		/// </summary>
	    [SitecoreField(FieldId = "{E8AB122C-6F54-4D4E-AEC6-F81ADDC558FC}")]
		Link TeaserLink { get; set; }

		/// <summary>
		/// Teaser summary
		/// </summary>
	    [SitecoreField(FieldId = "{13D97A52-7C4E-407C-960D-FADDE8A3C1B1}")]
		string TeaserSummary { get; set; }

		#endregion

	}
}
