// <autogenerated>
//   This file was generated by T4 code generator Generate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

namespace WageWorks.Feature.Navigation.Models.Glass
{
	using System;
    using System.Collections.Generic;
	using System.Collections.Specialized;
    using global::Glass.Mapper.Sc.Configuration;
    using global::Glass.Mapper.Sc.Configuration.Attributes;
	using global::Glass.Mapper.Sc.Fields;
    

	/// <summary>
	/// Represents a mapped type for item {58EB97A6-E28F-44CE-AF23-5CF6CD2B4924} in Sitecore.
	/// Path: /sitecore/templates/Feature/Navigation/_Anchor
	/// </summary>
	[SitecoreType(TemplateId = "{58EB97A6-E28F-44CE-AF23-5CF6CD2B4924}")]
	public partial interface IAnchor
	{
        [SitecoreId]
        Guid Id { get; set; }
		#region Navigation
	    [SitecoreField(FieldId = "{A2EC2913-59CC-4F88-933B-91076D2E956B}")]
		string AnchorName { get; set; }

		#endregion

	}
}
